# This is a basic workflow to help you get started with Actions

name: Frontend CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - master
    paths:
      - PreciseAlloy.Frontend/**
      - .github/workflows/frontend-deploy.yml

  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - PreciseAlloy.Frontend/**
      - .github/workflows/frontend-deploy.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    timeout-minutes: 5
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Base 🛎️
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: master

      - name: Setup Bun 🛎️
        uses: oven-sh/setup-bun@v2

      - name: Bun Install
        run: bun install
        working-directory: PreciseAlloy.Frontend

      - name: Lint
        run: bun run lint
        working-directory: PreciseAlloy.Frontend

      - name: ESHN check
        run: bun run eshn
        working-directory: PreciseAlloy.Frontend

      - name: INTE check
        run: bun run inte
        working-directory: PreciseAlloy.Frontend
